export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FAIL = 'AUTH_FAIL';
export const CHECK_VERIFY = 'CHECK_VERIFY';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const FETCH_SENTENCES = 'FETCH_SENTENCES';
export const PRACTICE_DONE = 'PRACTICE_DONE';

export const CHANGE_START = 'CHANGE_START';
export const CHANGE_SUCCESS = 'CHANGE_SUCCESS';
export const CHANGE_FAIL = 'CHANGE_FAIL';
export const CHANGE_USERNAME_OR_EMAIL = 'CHANGE_USERNAME_OR_EMAIL';
export const RESET_PROGRESS = 'RESET_PROGRESS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';